using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;

namespace Torch
{
    internal class RunCmd
    {
        public static string Exec(string cmd, string args = null)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "python";
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            using (StreamReader reader = process.StandardOutput)
            {
                string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script

                if (!string.IsNullOrEmpty(stderr))
                    Console.WriteLine(stderr);

                var result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                Console.WriteLine(result);
                return result;
            }
        }
    }
}
