// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Applies SoftMax over features to each spatial location.<br></br>
            ///	
            ///	When given an image of Channels x Height x Width, it will
            ///	apply Softmax to each location \((Channels, h_i, w_j)\)
            /// </summary>
            public partial class Softmax2d : Module
            {
                // auto-generated class
                
                public Softmax2d(PyObject pyobj) : base(pyobj) { }
                
                public Softmax2d(Module other) : base(other.PyObject as PyObject) { }
                
                
            }
        }
    }
    
}
