// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Applies the element-wise function:
            ///	
            ///	\[\text{SoftSign}(x) = \frac{x}{ 1 + |x|}
            ///	
            ///	\]
            /// </summary>
            public partial class Softsign : Module
            {
                // auto-generated class
                
                public Softsign(PyObject pyobj) : base(pyobj) { }
                
                public Softsign(Module other) : base(other.PyObject as PyObject) { }
                
                
            }
        }
    }
    
}
