// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Applies a 1D average pooling over an input signal composed of several
            ///	input planes.<br></br>
            ///	
            ///	In the simplest case, the output value of the layer with input size \((N, C, L)\),
            ///	output \((N, C, L_{out})\) and kernel_size \(k\)
            ///	can be precisely described as:
            ///	
            ///	\[\text{out}(N_i, C_j, l) = \frac{1}{k} \sum_{m=0}^{k-1}
            ///	                       \text{input}(N_i, C_j, \text{stride} \times l + m)\]
            ///	
            ///	If padding is non-zero, then the input is implicitly zero-padded on both sides
            ///	for padding number of points.<br></br>
            ///	
            ///	The parameters kernel_size, stride, padding can each be
            ///	an int or a one-element tuple.
            /// </summary>
            public partial class AvgPool1d : Module
            {
                // auto-generated class
                
                public AvgPool1d(PyObject pyobj) : base(pyobj) { }
                
                public AvgPool1d(Module other) : base(other.PyObject as PyObject) { }
                
                public AvgPool1d(int kernel_size, int? stride = null, int? padding = 0, bool? ceil_mode = null, bool? count_include_pad = null)
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(new object[]
                    {
                        kernel_size,
                    });
                    var kwargs=new PyDict();
                    if (stride!=null) kwargs["stride"]=ToPython(stride);
                    if (padding!=0) kwargs["padding"]=ToPython(padding);
                    if (ceil_mode!=null) kwargs["ceil_mode"]=ToPython(ceil_mode);
                    if (count_include_pad!=null) kwargs["count_include_pad"]=ToPython(count_include_pad);
                    dynamic py = __self__.InvokeMethod("AvgPool1d", pyargs, kwargs);
                    self=py as PyObject;
                }
                
            }
        }
    }
    
}
