// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Creates a criterion that measures the Binary Cross Entropy
            ///	between the target and the output:
            ///	
            ///	The unreduced (i.e.<br></br>
            ///	 with reduction set to 'none') loss can be described as:
            ///	
            ///	\[\ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
            ///	l_n = - w_n \left[ y_n \cdot \log x_n + (1 - y_n) \cdot \log (1 - x_n) \right],
            ///	
            ///	\]
            ///	
            ///	where \(N\) is the batch size.<br></br>
            ///	 If reduction is not 'none'
            ///	(default 'mean'), then
            ///	
            ///	\[\ell(x, y) = \begin{cases}
            ///	    \operatorname{mean}(L), & \text{if reduction} = \text{'mean';}\\
            ///	    \operatorname{sum}(L),  & \text{if reduction} = \text{'sum'.}
            ///	\end{cases}
            ///	
            ///	\]
            ///	
            ///	This is used for measuring the error of a reconstruction in for example
            ///	an auto-encoder.<br></br>
            ///	 Note that the targets \(y\) should be numbers
            ///	between 0 and 1.
            /// </summary>
            public partial class BCELoss : Module
            {
                // auto-generated class
                
                public BCELoss(PyObject pyobj) : base(pyobj) { }
                
                public BCELoss(Module other) : base(other.PyObject as PyObject) { }
                
                public BCELoss(Tensor weight = null, bool? size_average = null, bool? reduce = null, string reduction = "mean")
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(new object[]
                    {
                    });
                    var kwargs=new PyDict();
                    if (weight!=null) kwargs["weight"]=ToPython(weight);
                    if (size_average!=null) kwargs["size_average"]=ToPython(size_average);
                    if (reduce!=null) kwargs["reduce"]=ToPython(reduce);
                    if (reduction!="mean") kwargs["reduction"]=ToPython(reduction);
                    dynamic py = __self__.InvokeMethod("BCELoss", pyargs, kwargs);
                    self=py as PyObject;
                }
                
            }
        }
    }
    
}
