// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Applies the rectified linear unit function element-wise:
            ///	
            ///	\(\text{ReLU}(x)= \max(0, x)\)
            /// </summary>
            public partial class ReLU : Module
            {
                // auto-generated class
                
                public ReLU(PyObject pyobj) : base(pyobj) { }
                
                public ReLU(Module other) : base(other.PyObject as PyObject) { }
                
                public ReLU(bool? inplace = false)
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(new object[]
                    {
                    });
                    var kwargs=new PyDict();
                    if (inplace!=false) kwargs["inplace"]=ToPython(inplace);
                    dynamic py = __self__.InvokeMethod("ReLU", pyargs, kwargs);
                    self=py as PyObject;
                }
                
            }
        }
    }
    
}
