// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Applies the element-wise function:
            ///	
            ///	\[\text{ReLU6}(x) = \min(\max(0,x), 6)
            ///	
            ///	\]
            /// </summary>
            public partial class ReLU6 : Module
            {
                // auto-generated class
                
                public ReLU6(PyObject pyobj) : base(pyobj) { }
                
                public ReLU6(Module other) : base(other.PyObject as PyObject) { }
                
                public ReLU6(bool? inplace = false)
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(new object[]
                    {
                    });
                    var kwargs=new PyDict();
                    if (inplace!=false) kwargs["inplace"]=ToPython(inplace);
                    dynamic py = __self__.InvokeMethod("ReLU6", pyargs, kwargs);
                    self=py as PyObject;
                }
                
            }
        }
    }
    
}
