// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Applies a 2D average pooling over an input signal composed of several input
            ///	planes.<br></br>
            ///	
            ///	In the simplest case, the output value of the layer with input size \((N, C, H, W)\),
            ///	output \((N, C, H_{out}, W_{out})\) and kernel_size \((kH, kW)\)
            ///	can be precisely described as:
            ///	
            ///	\[out(N_i, C_j, h, w)  = \frac{1}{kH * kW} \sum_{m=0}^{kH-1} \sum_{n=0}^{kW-1}
            ///	                       input(N_i, C_j, stride[0] \times h + m, stride[1] \times w + n)\]
            ///	
            ///	If padding is non-zero, then the input is implicitly zero-padded on both sides
            ///	for padding number of points.<br></br>
            ///	
            ///	The parameters kernel_size, stride, padding can either be:
            ///	
            ///	a single int – in which case the same value is used for the height and width dimension
            ///	a tuple of two ints – in which case, the first int is used for the height dimension,
            ///	and the second int for the width dimension
            /// </summary>
            public partial class AvgPool2d : Module
            {
                // auto-generated class
                
                public AvgPool2d(PyObject pyobj) : base(pyobj) { }
                
                public AvgPool2d(Module other) : base(other.PyObject as PyObject) { }
                
                public AvgPool2d(int[] kernel_size, int[] stride = null, int? padding = 0, bool? ceil_mode = null, bool? count_include_pad = null)
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(new object[]
                    {
                        kernel_size,
                    });
                    var kwargs=new PyDict();
                    if (stride!=null) kwargs["stride"]=ToPython(stride);
                    if (padding!=0) kwargs["padding"]=ToPython(padding);
                    if (ceil_mode!=null) kwargs["ceil_mode"]=ToPython(ceil_mode);
                    if (count_include_pad!=null) kwargs["count_include_pad"]=ToPython(count_include_pad);
                    dynamic py = __self__.InvokeMethod("AvgPool2d", pyargs, kwargs);
                    self=py as PyObject;
                }
                
            }
        }
    }
    
}
