// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Applies a 3D average pooling over an input signal composed of several input
            ///	planes.<br></br>
            ///	
            ///	In the simplest case, the output value of the layer with input size \((N, C, D, H, W)\),
            ///	output \((N, C, D_{out}, H_{out}, W_{out})\) and kernel_size \((kD, kH, kW)\)
            ///	can be precisely described as:
            ///	
            ///	\[\begin{aligned}
            ///	    \text{out}(N_i, C_j, d, h, w) ={} & \sum_{k=0}^{kD-1} \sum_{m=0}^{kH-1} \sum_{n=0}^{kW-1} \\
            ///	                                      & \frac{\text{input}(N_i, C_j, \text{stride}[0] \times d + k,
            ///	                                              \text{stride}[1] \times h + m, \text{stride}[2] \times w + n)}
            ///	                                             {kD \times kH \times kW}
            ///	\end{aligned}
            ///	
            ///	\]
            ///	
            ///	If padding is non-zero, then the input is implicitly zero-padded on all three sides
            ///	for padding number of points.<br></br>
            ///	
            ///	The parameters kernel_size, stride can either be:
            ///	
            ///	a single int – in which case the same value is used for the depth, height and width dimension
            ///	a tuple of three ints – in which case, the first int is used for the depth dimension,
            ///	the second int for the height dimension and the third int for the width dimension
            /// </summary>
            public partial class AvgPool3d : Module
            {
                // auto-generated class
                
                public AvgPool3d(PyObject pyobj) : base(pyobj) { }
                
                public AvgPool3d(Module other) : base(other.PyObject as PyObject) { }
                
                public AvgPool3d(int[] kernel_size, int[] stride = null, int? padding = 0, bool? ceil_mode = null, bool? count_include_pad = null)
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(new object[]
                    {
                        kernel_size,
                    });
                    var kwargs=new PyDict();
                    if (stride!=null) kwargs["stride"]=ToPython(stride);
                    if (padding!=0) kwargs["padding"]=ToPython(padding);
                    if (ceil_mode!=null) kwargs["ceil_mode"]=ToPython(ceil_mode);
                    if (count_include_pad!=null) kwargs["count_include_pad"]=ToPython(count_include_pad);
                    dynamic py = __self__.InvokeMethod("AvgPool3d", pyargs, kwargs);
                    self=py as PyObject;
                }
                
            }
        }
    }
    
}
