// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Pads the input tensor using replication of the input boundary.<br></br>
            ///	
            ///	For N-dimensional padding, use torch.nn.functional.pad().
            /// </summary>
            public partial class ReplicationPad3d : Module
            {
                // auto-generated class
                
                public ReplicationPad3d(PyObject pyobj) : base(pyobj) { }
                
                public ReplicationPad3d(Module other) : base(other.PyObject as PyObject) { }
                
                public ReplicationPad3d(int padding = 0)
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(new object[]
                    {
                    });
                    var kwargs=new PyDict();
                    if (padding!=0) kwargs["padding"]=ToPython(padding);
                    dynamic py = __self__.InvokeMethod("ReplicationPad3d", pyargs, kwargs);
                    self=py as PyObject;
                }
                
            }
        }
    }
    
}
