// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Applies the HardTanh function element-wise
            ///	
            ///	HardTanh is defined as:
            ///	
            ///	\[\text{HardTanh}(x) = \begin{cases}
            ///	    1 & \text{ if } x > 1 \\
            ///	    -1 & \text{ if } x < -1 \\
            ///	    x & \text{ otherwise } \\
            ///	\end{cases}
            ///	
            ///	\]
            ///	
            ///	The range of the linear region \([-1, 1]\) can be adjusted using
            ///	min_val and max_val.
            /// </summary>
            public partial class Hardtanh : Module
            {
                // auto-generated class
                
                public Hardtanh(PyObject pyobj) : base(pyobj) { }
                
                public Hardtanh(Module other) : base(other.PyObject as PyObject) { }
                
                public Hardtanh(double min_val = -1.0, double max_val = 1.0, bool inplace = false)
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(new object[]
                    {
                    });
                    var kwargs=new PyDict();
                    if (min_val!=-1.0) kwargs["min_val"]=ToPython(min_val);
                    if (max_val!=1.0) kwargs["max_val"]=ToPython(max_val);
                    if (inplace!=false) kwargs["inplace"]=ToPython(inplace);
                    dynamic py = __self__.InvokeMethod("Hardtanh", pyargs, kwargs);
                    self=py as PyObject;
                }
                
            }
        }
    }
    
}
