// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            ///	Applies a linear transformation to the incoming data: \(y = xA^T + b\)
            /// </summary>
            public partial class Linear : Module
            {
                // auto-generated class
                
                public Linear(PyObject pyobj) : base(pyobj) { }
                
                public Linear(Module other) : base(other.PyObject as PyObject) { }
                
                public Linear(int in_features, int out_features, bool bias = true)
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(new object[]
                    {
                        in_features,
                        out_features,
                    });
                    var kwargs=new PyDict();
                    if (bias!=true) kwargs["bias"]=ToPython(bias);
                    dynamic py = __self__.InvokeMethod("Linear", pyargs, kwargs);
                    self=py as PyObject;
                }
                
            }
        }
    }
    
}
